//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace HeathenEngineering.OSK.v2
{
	public delegate void KeyboardEventHandler(OnScreenKeyboard sender, OnScreenKeyboardArguments e);
	
	/// <summary>
	/// On screen keyboard arguments.
	/// </summary>
	public class OnScreenKeyboardArguments
	{
		/// <summary>
		/// The key pressed.
		/// </summary>
		public OnScreenKeyboardKey KeyPressed;
		
		/// <summary>
		/// Initializes a new instance of the <see cref="OnScreenKeyboardArguments"/> class.
		/// </summary>
		/// <param name="KeyPressed">Key pressed.</param>
		public OnScreenKeyboardArguments (OnScreenKeyboardKey KeyPressed)
		{
			this.KeyPressed = KeyPressed;
		}
	}
}
