//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

namespace HeathenEngineering.OSK.v2
{
	public class OnScreenKeyboardRowBuilder
	{
		public bool FoldOut = false;
		public int keyCount = 14;
		public List<KeyCode> keyCodeValues = new List<KeyCode>();
		public List<string> upperValues = new List<string>();
		public List<string> lowerValues = new List<string>();
		public List<KeyClass> types = new List<KeyClass>();
		
		public float KeyShiftHorizontal = 1.1f;
		public float RowShiftHorizontal = 0;
		
		public OnScreenKeyboardRowBuilder ()
		{
		}
	}
}
